@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI5MjUzMTN9.bFHs_4gMNhgCDoxOqIjnPdBFrFb0vFxmxhDk5L6khbY


### User Create Request
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Kyle",
  "email": "kyle@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}



### Conversation Index Request
GET http://localhost:3000/conversations.json
Authorization: Bearer {{jwt}}

### Conversation Create Request
POST http://localhost:3000/conversations.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "sender_id": "1",
  "recipient_id": "2"
}

### Message Index Request
GET http://localhost:3000/messages.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "conversation_id": "2"
}