### User Create Route
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Kyle",
  "email": "kyle@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Conversation Index Route
GET http://localhost:3000/conversations/messages.json


### Conversation Show Route
GET http://localhost:3000/conversations/1/messages.json

